openapi: 3.1.0
info:
  title: DTO Schemas
  version: 1.0.0
components:
  schemas:
    DemoMessage:
      $ref: ./schemas/demo-message.json#/components/schemas/DemoMessage
    Item:
      $ref: ./schemas/item.json#/components/schemas/Item
